# Generated by Django 2.0.6 on 2018-07-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=40)),
                ('doc_type', models.CharField(max_length=4)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('phone_no', models.CharField(max_length=10)),
                ('signup_date', models.DateTimeField(verbose_name='date signed up')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='pub_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.User'),
        ),
    ]
