# Generated by Django 2.0.6 on 2018-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.FileField(max_length=40, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_date',
            field=models.DateTimeField(verbose_name='Registered Date'),
        ),
    ]
